// Chrome extensions cannot import outside their root. Bundle the canonical,
// dependency-free Studio renderer without changing its implementation.
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
export async function cursorBundle() {
  const parts = await Promise.all(['motions.js', 'config.js', 'engine.js'].map(
    file => readFile(resolve(root, 'companion/src', file), 'utf8')));
  const body = parts.map(source => source.replace(/\r\n/g, '\n').replace(/^import .*?;\n/gm, '')
    .replace(/^export /gm, '')).join('\n');
  return '// Generated by integration/sync-cursor.mjs from companion/src. Do not edit.\n'
    + 'export function cursorRuntime() {\n' + body
    + '\nreturn { Character, defaults, validatePack, poseFor, drawCursor };\n}\n';
}
export async function syncCursor(check = false) {
  const target = resolve(root, 'browser/extension/character-runtime.mjs');
  const source = await cursorBundle();
  if (check) {
    if ((await readFile(target, 'utf8')).replace(/\r\n/g, '\n') !== source) throw Error('Shared cursor is stale. Run npm run sync:cursor at the repository root.');
  } else await writeFile(target, source);
}
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  await syncCursor(process.argv.includes('--check'));
}
